### ISSUE TITLE
opam release compatible with 4.07.0

### ISSUE THREAD

**Issue by jvillard** [ygrek/ocaml-extlib#48]
It would be great to have a new release of this library for 4.07.0. I see there's already a commit in the repo about that, I'm opening this issue to track this if that's ok.

**Comment by ygrek** [comment]
Thanks for reminder.
I am wondering if this is related to infer and if yes, does it really need to use extlib-compat? I was hoping to phase it out completely one day, because there are better libraries for zip and utf8 support. Another alternative is to include these modules back in main lib under toplevel ExtLib module to avoid name conflicts (but this will break compatiblity a little)

**Comment by davidpichardie** [comment]
This is related to the library Javalib that is used by Infer. I maintain this library.
Which library do you recommend for utf8 support ?

**Comment by ygrek** [comment]
I believe uutf will fulfil JParseSignature needs, e.g. read_utf8 will use Uutf.String.fold_utf_8
And Uchar is part of stdlib, so will only need to raise min ocaml version by one (to 4.03).

**Comment by ygrek** [comment]
uh, I understand you were talking about extlib-compat.
So, as I said above - I would like to get rid of it because it is a nuisance to maintain and of low usability given toplevel module names conflicting with many other libraries. OTOH I don't want to break reverse depending code needlessly. So please let me know if you would rather switch javalib to uutf or I should make another release of extlib-compat or I should move utf8 stuff into ExtLib module to avoid conflicts?

**Comment by ygrek** [comment]
Hm, camomile seems to be much more heavyweight..
Thanks!
